### ISSUE TITLE
Bundle CSS and other non-JS files

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#153]
Currently CSS and other non-JS files are not copied to the `dist` directory. This makes some components unusable when published. To solve this we either need a bundler, or just copy the CSS and other files to the `dist` directory. (For some components, this has been temporarily fixed by using `copyfiles` to manually move the css files to the dist folder. But the CSS is not minified if we do that.)

Rollup seems to be the best choice for a component library. The config can be copied and build upon from https://tsdx.io/

We should also validate that component css works in an external (create-react) app. Currently, the styles are not applied when we use `.module.css` files.

### Tasks
- [x] Configure rollup to create a single JS file.
- [x] SVG are bundled and processed with SVGO
- [x] Install PostCSS, with the PostCSS Logical Properties and Values plugin (/w auto prefixer)
- [x] Test in clean react app

**Comment by bddjong** [comment]
I think we might want a bit more elaborate investigation into which bundler suits our needs. If an investigation has already been done, can we add a short summary here as to the benefits and downsides of some of our options?

**Comment by bddjong** [comment]
postcss-logical generates CSS which is unsupported by Chrome. Removing it from the issue requirements.
