### ISSUE TITLE
Missing Component: ListItemIcon

### ISSUE THREAD

**Issue by DanielvanVliet** [nl-design-system/denhaag#21]
In order to display icons in Lists, Select and other MUI based components we will need the [ListItemIcon ](https://material-ui.com/api/list-item-icon/)component.
It is usually used within a ListItem, or a MenuItem.

This issue is related to #19 since both are a result of using MUI components within stories, instead of only using nlds-react components.

**Tasks**

- [ ] Add a new wrapped ListItemIcon component, in the correct hierarchy/folder
- [ ] Updated stories that are using ListItemIcon from MUI to use our wrapped ListItemIcon
- [ ] Add new/update story that uses the ListItemIcon within one or more components:  List, Select, Menu
