### ISSUE TITLE
Restructure directories and packages

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#27]
Currently, if you install the root package you'll get all components three times. This is because of the nested package structure we currently have. This is not desirable. ~~In addition, component's .tsx files are provided as is, meaning that the developer who installs the components gets the raw .tsx files. Usually you want to transpile the ts to js and provide a Typescript type file and/or transpile esx to es2017, which 90% of the browser support. This way developers can use both Javascript and Typescript.~~

**Tasks**: 
- [x] Flatten the directory structure such that every component is directly in the `src/components` directory. ~~The group components like `surfaces` and `input` can be moved to `src/groups` (for example) for clarity as their only purpose is to group components.~~
- [ ] ~~consolidate some components into one package as it makes little sense to use one without the other:~~
  * ~~Components into `tab`~~
    * ~~tab~~
    * ~~tabcontext~~
    * ~~tablist~~
    * ~~tabpanel~~
    * ~~tabs~~
    * ~~tabscrollbutton~~
  * ~~Components into `menu`~~
    * ~~menuitem~~
    * ~~menulist~~
    * ~~popover~~
    * ~~popper~~
  * ~~Components into `list`~~
    * ~~listitem~~
    * ~~listitemavatar~~
    * ~~listitemicon~~
    * ~~listitemsecondaryaction~~
    * ~~listitemtext~~
    * ~~listsubheader~~
  * ~~Components into `avatar`~~
    * ~~avatargroup~~
  * ~~Components into `card`~~
    *  ~~cardactions~~
    * ~~cardcontent~~
    * ~~cardheader~~
    * ~~paper~~
  * ~~Components into `accordion`~~
    * ~~accordionactions~~
    * ~~accordiondetails~~
    * ~~accordionsummary~~
- [ ] ~~Create an index.tsx files when needed.~~
- [ ] ~~Fix installed package files. TBD~~
- [x] Test if components install correctly.
