### ISSUE TITLE
Add README.md to every component

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#28]
Currently, none of the components have a README.md file. When you go to the published package site you don't get any useful information about the component. I suggest creating at least a basic README with a link to the correct Storybook page.

**Tasks**:

- [ ] Install [markdownlint](https://github.com/DavidAnson/markdownlint), like [nl-design-system](https://github.com/nl-design-system/web-component-poc). Add it to lint-staged.
- [ ] Develop a README template which can be used for all components.
    - Link to the component in Storybook
    - Description of component
    - Use cases for component
- [ ] Add this template to every component

**Comment by GewoonMaarten** [comment]
This will be tracked for each component individually.
