### ISSUE TITLE
Automated Versioning: take advantage of Lerna Conventional Commit

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#43]
Currently, if we want to bump the version of the package we have to do this manually. Lerna supposedly (it is not documented very well) provides functionality which looks at your commit history to automatically update the packages. To make use of this our commit messages need to adhere to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) structure.

Sources:
- https://gist.github.com/draganjakovljevic/81db0a71b5d277935526099410bd79c0#file-final_lerna-json
- https://github.com/lerna/lerna/blob/main/commands/version/README.md

**Tasks**
- [x] Test if this actually works. (If not, close this issue)
- [ ] Configure Lerna such that it knows we use Conventional Commits.
- [x] Install a linter to check if we adhere to Conventional Commits.
